# Generated by Django 5.1.1 on 2024-09-12 14:35

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Type your post title here', max_length=200, validators=[blog.validators.validate_title], verbose_name='Post title'),
        ),
    ]
